### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by rignaneseleo**

### CODE REVIEW

**Comment by denbonte** [comment]
@rignaneseleo not sure this is a typo though - it's just the British spelling. 
As they aim to provide the app also in British English, I assume all the documentation will be following such spelling rules: see also the use of "minimises" instead of "minimizes" etc.

I'd personally avoid opening silly requests but yeah, that's just me.

**Comment by himynameisfuego** [comment]
Although I prefer US english to UK english, all the documentation seems to be provided in british english, hence making this typo fix not only useless but also utterly wrong.
"Lasciamelo dire, questo typofix... è molto italiano. Molto italiano"

**Comment by rignaneseleo** [comment]
Thanks for the explanation, peace out ✌🏼

**Comment by luke10ferrari** [comment]
Thanks @rignaneseleo! I confirm that we elected to write all the documentation in British English, and that this explains the "s" in place of the perhaps more familiar "z."

**Pull request closed without merging**
